# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1winJkx_Gx-5vw0jjNuDWNPDFj0bFBYtt
"""

pip install opencv-python

from google.colab.patches import cv2_imshow
import cv2
rasm = cv2.imread("pxfuel.jpg")
cv2_imshow(rasm)

oqqora = cv2.cvtColor(rasm,cv2.COLOR_BGR2GRAY)
cv2_imshow(oqqora)

from google.colab.patches import cv2_imshow
import cv2
rasm1= cv2.imread("1374683.png")
cv2_imshow(rasm1)

oqqora = cv2.cvtColor(rasm1,cv2.COLOR_BGR2GRAY)
cv2_imshow(oqqora)

from google.colab.patches import cv2_imshow
import cv2
rasm2= cv2.imread("1326237.png")
cv2_imshow(rasm2)

oqqora = cv2.cvtColor(rasm2,cv2.COLOR_BGR2GRAY)
cv2_imshow(oqqora)

from google.colab.patches import cv2_imshow
import cv2
rasm3= cv2.imread("gojo-satoru-holding-his-face-iyrluirbzvncz77a.jpg")
cv2_imshow(rasm3)

oqqora = cv2.cvtColor(rasm3,cv2.COLOR_BGR2GRAY)
cv2_imshow(oqqora)

from google.colab.patches import cv2_imshow
import cv2
rasm4= cv2.imread("smirk-gojo-pfp-vtku3m196cdxoida.jpg")
cv2_imshow(rasm4)

oqqora = cv2.cvtColor(rasm4,cv2.COLOR_BGR2GRAY)
cv2_imshow(oqqora)